#!/usr/bin/env python3
"""Export 2008-2009 NICC PDF pages that hold image-only GACC / cause charts.

Renders high-res PNGs under data/nicc-source/ocr-pages/ for hand transcription
or local OCR (tesseract / macOS Vision). Does not invent acre numbers.

Usage:
  python scripts/export_nicc_gap_pages.py
"""

from __future__ import annotations

from pathlib import Path

import fitz  # PyMuPDF

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "data" / "nicc-source"
OUT = SRC / "ocr-pages"

# 0-based page indices from pdfplumber probes (2026-07-16).
JOBS = [
    # Lightning / human charts + agency×GACC multiyear table
    (2008, "annual_report_2008_508.pdf", [20, 21, 23]),
    (2009, "annual_report_2009_508.pdf", [21, 22, 24]),
]


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    for year, pdf_name, pages in JOBS:
        path = SRC / pdf_name
        if not path.exists():
            raise SystemExit(f"Missing PDF: {path}")
        doc = fitz.open(path)
        for p in pages:
            page = doc[p]
            pix = page.get_pixmap(matrix=fitz.Matrix(2, 2), alpha=False)
            out = OUT / f"{year}_p{p + 1}.png"
            pix.save(str(out))
            print(f"wrote {out} ({pix.width}x{pix.height})")
        doc.close()
    readme = OUT / "README.md"
    readme.write_text(
        "# OCR / hand-extract pages (2008-2009)\n\n"
        "Generated by `scripts/export_nicc_gap_pages.py`.\n\n"
        "These PNGs are the image-only NICC pages that block machine extract of\n"
        "regional GACC acres and lightning/human cause acres. Transcribe into\n"
        "`data/gacc-2008-2009-hand-extract-template.csv`, then fold into\n"
        "`scripts/build_western_acres.py` / `data/regional-acres-annual.csv`.\n\n"
        "PNGs are regeneratable; see `.gitignore` if not committing binaries.\n",
        encoding="utf-8",
    )
    print(f"wrote {readme}")


if __name__ == "__main__":
    main()
